apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: c3VwZXJzZWNyZXQ=  # "supersecret"의 base64 인코딩 값
  mysql-database: bXlkYg==               # "mydb"의 base64 인코딩 값
  mysql-user: dXNlcg==                   # "user"의 base64 인코딩 값
  mysql-password: c2VjdXJlcGFzcw==       # "securepass"의 base64 인코딩 값
